<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MegaMindsTechProject.DAL\MegaMindsTechProject.DAL.csproj" />
    <ProjectReference Include="..\MegaMindsTechProject.Model\MegaMindsTechProject.Model.csproj" />
  </ItemGroup>

</Project>
